core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from django.conf.urls import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# handler404 = 'main.views.error_404'

core/main/urls.py
from django.urls import path
from .views import (Home,car_shop,mashin_yuish,model10,yetgazib_berish,
                    Login,signup,profile,cars,car_detail,Logout,comment_qoshish,delete,
                    cart,cart_yangilash,hamma_model,error_404)

urlpatterns = [
    path('',Home,name='Home'),
    path('car_shop/',car_shop,name='car_shop'),
    path('mashin_yuish/',mashin_yuish,name='mashin_yuish'),
    path('comment/',model10,name='model10'),
    path("delete/comment/<int:comment_id>/", delete, name="delete_comment"),
    path('yetgazib_berish/<int:car_detail_id>/',yetgazib_berish,name='yetgazib_berish'),
    path('login/',Login,name='login'),
    path('Logout/',Logout,name='Logout'),
    path('signup/',signup,name='signup'),
    path("profile/", profile, name="profile"),
    path("profile/<str:username>/", profile, name="profile"),
    path('cars/',cars,name='cars'),
    path('cars/<int:car_model_id>/',cars,name='car_model'),
    path('car_detail/<int:car_id>/',car_detail,name='car_detail'),
    path('comment_qoshish/',comment_qoshish,name='comment_qoshish'),
    path('cart/',cart,name='cart'),
    path('cart_yangilash/',cart_yangilash,name='cart_yangilash'),
    path('hamma_model/<str:m_model>/',hamma_model,name='hamma_model'),
    path('error_404/',error_404,name='error_404')

]

core/main/models.py
from django.db import models
from django.core.validators import MaxValueValidator,MinValueValidator
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser


#<=============================================================================>

class User(AbstractUser):
    image = models.ImageField(upload_to='user_images/',null=True,blank=True)
    

class biz_haqmizda_ga(models.Model):
    img = models.ImageField(upload_to='rasim/')
    name = models.CharField(max_length=20)
    text = models.TextField(max_length=100)

    def __str__(self):
        return self.name

class bizning_asosiy_qoydlar(models.Model):
    img_orqa = models.ImageField(upload_to='img_orqa/')
    img_oldi = models.ImageField(upload_to='img_oldi/')
    name = models.CharField(max_length=50)
    sarlavha =models.CharField(max_length=100)
    text = models.TextField(max_length=300)

    def __str__(self):
        return self.name
   

class mashin_shop(models.Model):
    img  = models.ImageField(upload_to='shop_img/')
    name = models.CharField(max_length=100)
    Seats = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(5)])
    Suitcase = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(3)])
    text = models.TextField(max_length=300)

    def __str__(self):
        return self.name 
    
    @property
    def hamma_car(self):
        return self.cars.all()
    
class car(models.Model):
    img = models.ImageField(upload_to='img_cars/')
    name = models.CharField(max_length=50)
    price = models.DecimalField(decimal_places=1, max_digits=10, default=0.0)
    discount = models.DecimalField(decimal_places=1, max_digits=10, default=0.0)
    car_sh = models.ForeignKey(mashin_shop, on_delete=models.CASCADE, related_name="cars")
    km = models.IntegerField()
    cc = models.IntegerField()

    def __str__(self):
        return self.name


class VehicleImage(models.Model):
    image = models.ImageField(upload_to='vehicles/')
    car_a = models.ForeignKey('car_details',on_delete=models.CASCADE,related_name='car_a')

    def __str__(self):
        return f"Imge {self.id}"

class car_details(models.Model):
    TYPE_CHOICES = [
        ('new', 'New'),
        ('used', 'Used vehicle'),
    ]
    FUEL_CHOICES = [
        ('diesel', 'Diesel'),
        ('petrol', 'Petrol'),
        ('electric', 'Electric'),
    ]
    GEARBOX_CHOICES = [
        ('manual', 'Manual'),
        ('automatic', 'Automatic'),
    ]
    type = models.CharField(max_length=10, choices=TYPE_CHOICES, default='used')
    make = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    first_registration = models.DateField()
    mileage = models.PositiveIntegerField()
    fuel = models.CharField(max_length=10, choices=FUEL_CHOICES, default='diesel')
    engine_size = models.PositiveIntegerField()
    power = models.PositiveIntegerField()
    gearbox = models.CharField(max_length=10, choices=GEARBOX_CHOICES, default='manual')
    number_of_seats = models.PositiveIntegerField()
    doors = models.CharField(max_length=5)
    color = models.CharField(max_length=50)
    main_image = models.ImageField(upload_to='vehicles/')
    car = models.ForeignKey(car, on_delete=models.CASCADE, related_name="car_d")

    def __str__(self):
        return self.model 
    
    def car_hamma(self):
        return self.car_d.all()
    
    @property
    def all_images(self):
        if self.car_a.all():
            return self.car_a.all()

class modeli(models.Model):
    img = models.ImageField(upload_to='model/')
    name = models.CharField(max_length=100)
    text = models.TextField(max_length=500)

    def __str__(self):
        return self.name
    
class model_a(models.Model):
    img = models.ImageField(upload_to='model_a/')

    def __str__(self):
        return f"Img {self.id}"

class Comment(models.Model):
    user = models.ForeignKey(get_user_model(),on_delete=models.CASCADE)
    comment_sarlavha = models.CharField(max_length=25)
    comment = models.CharField(max_length=400)

    def __str__(self):
        return f'comment shu user niki:|{self.user.username}'
    


class mashin_yuish_uchun(models.Model):
    user = models.OneToOneField(get_user_model(),on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    mobile_no = models.CharField(max_length=20)
    date = models.DateField()
    message = models.TextField()

    def __str__(self):
        return self.name



class Address(models.Model):
  
    country_choices = [
        ("RU", "Rossiya"),
        ("UZ", "O'ZBEKISTON"),
    ]

    user = models.ForeignKey(get_user_model(),on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    mobile_no = models.CharField(max_length=15)
    address_line1 = models.CharField(max_length=255)
    address_line2 = models.CharField(max_length=255, blank=True, null=True)
    country = models.CharField(max_length=200, choices=country_choices, default="UZ")
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    zip_code = models.CharField(max_length=10)
    car_det = models.ForeignKey(car_details,on_delete=models.CASCADE,related_name='car_det')


    def __str__(self):
        return f"{self.first_name} {self.last_name} - {self.address_line1}"
    

class CreditCard(models.Model):
    user = models.OneToOneField(get_user_model(),on_delete=models.CASCADE)
    number = models.CharField(max_length=16)
    holder = models.CharField(max_length=20)
    expiration_month = models.CharField(max_length=2)
    expiration_year = models.CharField(max_length=4)
    ccv = models.CharField(max_length=3)

    def __str__(self):
        return f"{self.holder} - **** **** **** {self.number[-4:]}"
    

core/main/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import get_user_model
from django.http import HttpResponseNotFound
from django.http import HttpResponse
from .forms import LoginForm,SignupForm,CommentForm,mashin_yuvishForm,AddressForm,CreditCardForm
from django.contrib.auth import login, authenticate, logout
from .models import (biz_haqmizda_ga,bizning_asosiy_qoydlar,mashin_shop,modeli,
                     model_a,Comment,car,car_details,mashin_yuish_uchun,Address,CreditCard)
from django.http import Http404
from django.contrib import messages
from django.conf.urls import handler404
# Create your views here.


def car_shop(request):
    context = {
        'css':'css/car-shop.css',
        'car_shop':mashin_shop.objects.all()
    }
    return render(request,'car-shop.html',context=context)


def Home(request):
    context = {
        'css':'css/Home.css'
    }
    return render(request,'Home.html',context=context)


def mashin_yuish(request):
    if not request.user.is_authenticated:
        return redirect("login")
    
    try:
        contact_message = mashin_yuish_uchun.objects.get(user=request.user)
    except mashin_yuish_uchun.DoesNotExist:
        contact_message = None

    if request.method == 'POST':
        form = mashin_yuvishForm(request.POST)
        if form.is_valid():
            contact_message = form.save(commit=False)
            contact_message.user = request.user
            contact_message.save()
            text = 'sizning malmuotlaringiz saqladi'
        text = "uzur sizning malmuotlaringiz saqlmadi"

    
    else:
        form = mashin_yuvishForm()
        text = ""
    
    context = {
        'css':'css/mashin-yuvish.css',
        'form':form,
        'text':text
    }
    return render(request,'mashin-yuvish.html',context=context)


def model10(request):
    if not request.user.is_authenticated:
        return redirect("login")
    
    context = {
        'css':'css/model10.css',
        'comment':Comment.objects.all(),
    }
    return render(request,'model10.html',context=context)


def error_404(request, exception):
    return render(request, '404.html', status=404)

handler404 = error_404

def yetgazib_berish(request,car_detail_id):
    
    form = AddressForm
    if request.method == "POST" and car_detail_id:
        
        if not request.user.is_authenticated:
            return redirect("login")
        form = AddressForm(request.POST)
        
        if form.is_valid():
            car = form.save(commit=False)
            car.user = request.user
            car.car_det = car_details.objects.get(pk=car_detail_id)
            car.save()

            return redirect("cart")

    context = {
        'css':'css/yetgazib-berish.css',
        'billing_form': form,
    }
    return render(request,'yetgazib-berish.html',context=context)

def Login(request):
    form = LoginForm()
    error = ""
    if request.method == "POST":
        form = LoginForm(request.POST)

        if form.is_valid():
            
            data = form.cleaned_data
            
            user = authenticate(username=data["username"], password=data["password"])
            if user:
                login(request, user)

                return redirect("profile")
            
            error = "Login noto'g'ri"
    context = {
        'css':'css/login.css',
        'error':error,
        'form':form
    }
    return render(request,'login.html',context=context)

def signup(request):
    form = SignupForm()
    
    if request.method == "POST":
        password = request.POST.get("password")
        
        form = SignupForm(request.POST, request.FILES)
        
        if form.is_valid():
            user = form.save(commit=False)
            
            user.set_password(password)
            
            user.save()
            
            return redirect("login")
    
    context = {
        'css':'css/singnup.css',
        'form':form   
    }
    return render(request,'signup.html',context=context)

def profile(request,username=None):

    if username is not None and get_user_model().objects.filter(username=username).exists():
        user = get_user_model().objects.get(username=username)
    elif request.user.is_authenticated:
        user = request.user
    else: 
        user = None

    context = {
        'css':'css/profile.css',
        'user':user
    }
    return render(request,'profile.html',context=context)

def Logout(request):
    logout(request)
    
    return redirect("login")

def cars(request,car_model_id=None):

    context = {
        'css':'assets/css/style.css',
        'car':car.objects.all()
    }
    if car_model_id:
       context["car"] = car.objects.filter(car_sh=car_model_id)
       
    return render(request,'cars.html',context=context)

def car_detail(request,car_id):
    context = ''
    if car_id:
        context = {
        'css':'assets/css/style.css',
        'cars':car_details.objects.filter(car=car_id),
    }
    return render(request,'car-details.html',context=context)

def comment_qoshish(request):
    form = CommentForm()
    
    if request.method == "POST":
        
        if not request.user.is_authenticated:

            return redirect("login")
        form = CommentForm(request.POST)
        
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.save()
            form = CommentForm()
            return redirect('model10')

    context = {
        'css':'css/singnup.css',
        'form':form
    }
    return render(request,'comment_qoshish.html',context=context)

def delete(request,comment_id):
    try:
        comment = Comment.objects.get(pk=comment_id)
        if request.user == comment.user:
            comment.delete()
            return redirect('model10') 
        else:
            return HttpResponse("Siz bu kommentni o'chira olmaysiz", status=403) 
    except Comment.DoesNotExist:
        return HttpResponse("Komment topilmadi", status=404)  


def cart(request):
    if not request.user.is_authenticated:
        return redirect("login")
    
    
    if not CreditCard.objects.filter(user=request.user).exists():
        if request.method == 'POST':
            form = CreditCardForm(request.POST)
            if form.is_valid():
                card = form.save(commit=False)
                card.user = request.user
                card.save()
                text = 'Sizning kartangiz saqlandi.'
            else:
                text = 'Uzur kartani saqlashda xatolik yuz berdi.'
        else:
            form = CreditCardForm()
            text = ""
    else:
        form = CreditCardForm()
        text = "sizda karta bor"

    matn=["sizda karta bor",'Sizning kartangiz saqlandi.','Uzur kartani saqlashda xatolik yuz berdi.']
    return render(request, 'cart.html', context={'form': form, 'text': text,'matn':matn})

def cart_yangilash(request):
    if not request.user.is_authenticated:
        return redirect("login")
    
    text = ""
    form = CreditCardForm()
    if CreditCard.objects.filter(user=request.user).exists():
        card = CreditCard.objects.get(user=request.user)
        if request.method == 'POST':
            form = CreditCardForm(request.POST, instance=card)
            if form.is_valid():
                form.save()
                text = 'Sizning kartangiz yangilandi.'
            else:
                text = 'Uzur kartani yangilashda xatolik yuz berdi.'
        else:
            form = CreditCardForm(instance=card)
    else:
        return redirect('cart')
    
    matn=['Sizning kartangiz yangilandi.','Uzur kartani yangilashda xatolik yuz berdi.']
    return render(request, 'cart.html', context={'form': form, 'text': text,'matn':matn})

def hamma_model(request, m_model):

    model_map = {
        'biz_haqmizda': {
            'css':'css/Biz-haqmizda.css',
            'biz_haqmizda':biz_haqmizda_ga.objects.all(),
            'template':'Biz-haqmizda.html'
        },
        'bizning_asosiy_qoydlarmiz': {
            'css':'css/bizning-asosiy-qoydlarmiz.css',
            'bizning_asosiy_qoydlarmiz':bizning_asosiy_qoydlar.objects.all(),
            'template':'bizning-asosiy-qoydlarmiz.html'
        },
        'Galereya': {
            'css':'css/Galereya.css',
            'template':'Galereya.html'
        },
        'Komanda': {
            'css':'css/Komanda.css',
            'template':'Komanda.html'
        },
        'kontakt': {
            'css':'css/kontakt.css',
            'template':'kontakt.html'
        },
        'model': {
            'css': 'css/model.css',
            'model': modeli.objects.all(),
            'model_a': model_a.objects.all(),
            'template': 'model.html'
        },
        'model1': {
            'css': 'css/model1.css',
            'template': 'model1.html'
        },
        'model2': {
            'css': 'css/model2.css',
            'template': 'model2.html'
        },
        'model3': {
            'css': 'css/model3.css',
            'template': 'model3.html'
        },
        'model4': {
            'css': 'css/model4.css',
            'template': 'model4.html'
        },
        'model5': {
            'css': 'css/model5.css',
            'template': 'model5.html'
        },
        'model6': {
            'css': 'css/model6.css',
            'template': 'model6.html'
        },
        'model7': {
            'css': 'css/model7.css',
            'template': 'model7.html'
        },
        'model8': {
            'css': 'css/model8.css',
            'template': 'model8.html'
        },
        'model9': {
            'css': 'css/model9.css',
            'template': 'model9.html'
        },
        'model11': {
            'css': 'css/model11.css',
            'template': 'model11.html'
        },
        'Portfoliya': {
            'css':'css/Portfoliya.css',
            'template': 'Portfoliya.html'
        }
    }

    if m_model in model_map:

core/main/templates/car-details.html
{% extends "base.html" %}

{% load static %}

{% block container %}

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    
    <div id="video-container">
      <video id="video-background" autoplay loop muted>
        <source src="{% static 'video/u1jg07dkvpay5lz0ez0q.mp4' %}">
      </video>
      <div id="content">
        <h1>Bmw </h1>
        {% for c in cars%}
        <h3><small><del><sup>$</sup>{{c.car.price}} </del></small> &nbsp; <sup>$</sup>{{c.car.discount}}</h3>
        {% endfor %}
      </div>
    </div>


     <div class="services">
      <div class="container">
        <div class="row">
          <div class="services">
            <div class="container">
              <div class="row">
                {% for vehicle in cars %}
                <div class="col-md-7">
                  <div>
                    <img src="{{ vehicle.main_image.url }}" alt="" class="img-fluid wc-image">
                  </div>
                  <br>
                  <div class="row">
                    {% for image in vehicle.all_images %}
                    <div class="col-sm-4 col-6">
                      <div>
                        <img src="{{ image.image.url }}" alt="" class="img-fluid">
                      </div>
                      <br>
                    </div>
                    {% endfor %}
                  </div>
                  <br>
                </div>
                <div class="col-md-5">
                  <form action="#" method="post" class="form">
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item">
                        <div class="clearfix">
                          <span class="pull-left">Type</span>
                          <strong class="pull-right">{{ vehicle.get_type_display }}</strong>
                        </div>
                      </li>
                      <li class="list-group-item">
                        <div class="clearfix">
                          <span class="pull-left">Make</span>
                          <strong class="pull-right">{{ vehicle.make }}</strong>
                        </div>
                      </li>
                      <li class="list-group-item">
                        <div class="clearfix">
                          <span class="pull-left">Model</span>
                          <strong class="pull-right">{{ vehicle.model }}</strong>
                        </div>
                      </li>
                      <li class="list-group-item">
                        <div class="clearfix">
                          <span class="pull-left">First registration</span>
                          <strong class="pull-right">{{ vehicle.first_registration|date:"d/m/Y" }}</strong>
                        </div>
                      </li>
                      <li class="list-group-item">
                        <div class="clearfix">
                          <span class="pull-left">Mileage</span>
                          <strong class="pull-right">{{ vehicle.mileage }} km</strong>
                        </div>
                      </li>
                      <li class="list-group-item">
                        <div class="clearfix">
                          <span class="pull-left">Fuel</span>
                          <strong class="pull-right">{{ vehicle.get_fuel_display }}</strong>
                        </div>
                      </li>
                      <li class="list-group-item">
                        <div class="clearfix">
                          <span class="pull-left">Engine size</span>
                          <strong class="pull-right">{{ vehicle.engine_size }} cc</strong>
                        </div>
                      </li>
                      <li class="list-group-item">
                        <div class="clearfix">
                          <span class="pull-left">Power</span>
                          <strong class="pull-right">{{ vehicle.power }} hp</strong>
                        </div>
                      </li>
                      <li class="list-group-item">
                        <div class="clearfix">
                          <span class="pull-left">Gearbox</span>
                          <strong class="pull-right">{{ vehicle.get_gearbox_display }}</strong>
                        </div>
                      </li>
                      <li class="list-group-item">
                        <div class="clearfix">
                          <span class="pull-left">Number of seats</span>
                          <strong class="pull-right">{{ vehicle.number_of_seats }}</strong>
                        </div>
                      </li>
                      <li class="list-group-item">
                        <div class="clearfix">
                          <span class="pull-left">Doors</span>
                          <strong class="pull-right">{{ vehicle.doors }}</strong>
                        </div>
                      </li>
                      <li class="list-group-item">
                        <div class="clearfix">
                          <span class="pull-left">Color</span>
                          <strong class="pull-right">{{ vehicle.color }}</strong>
                        </div>
                      </li>
                      <a href="{% url 'yetgazib_berish' car_detail_id=vehicle.id %}" class="filled-button">View More</a>
                    </ul>
                  </form>
                  <br>
                </div>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>

        <br>

        <div class="row">
          <div class="col-md-8">
            <div class="tabs-content">
              <h4>Vehicle Description</h4>

              <p>- Colour coded bumpers<br>- Tinted glass<br>- Immobiliser<br>- Central locking - remote<br>- Passenger airbag<br>- Electric windows<br>- Rear head rests<br>- Radio<br>- CD player<br>- Ideal first car<br>- Warranty<br>- High level brake light<br>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

              <br>
            </div>
          </div> 

          <div class="col-md-4">
            <div class="tabs-content">
              <h4>Vehicle Extras</h4>

              <p>- ABS <br>-Leather seats <br>-Power Assisted Steering <br>-Electric heated seats <br>-New HU and AU <br>-Xenon headlights</p>
            </div>

            <br>
            <br>

            <div class="tabs-content">
              <h4>Contact Details</h4>

              <p>
                <span>Name</span>
              
                <br>
              
                <strong>MaxanovAzim</strong>
              </p>
              
              <p>
                <span>Phone</span>
              
                <br>
                
                <strong>
                  <a href="tel:+998-90-900-90-90">+998-90-900-90-90</a>
                </strong>
              </p>
              
              <p>
                <span>Mobile phone</span>
              
                <br>
                
                <strong>
                  <a href="tel:+998-99-999-99-99">+998-99-999-99-99</a>
                </strong>
              </p>
              
              <p>
                <span>Email</span>
              
                <br>
                
                <strong>
                  <a href="mailto:azimmaxanov9.com">azimmaxanov9.com</a>
                </strong>
              </p>
            </div>

            <br>
          </div>
        </div>

        <br>
        <br>
        <br>
      </div>
    </div>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Additional Scripts -->
    <script src="{% static 'assets/js/custom.js' %}"></script>

    <style>
      #video-container {
        position: relative;
        width: 100%;
        height: 70vh; 
        overflow: hidden;
    }
    
    #video-background {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        object-fit: cover; 
    }
    
    #content {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%,-50%);
        text-align: center;
        color: #ffffff;
    }
    </style>
   
  
{% endblock %}